version: '3'

services:
    db:
        image: postgres
    redis:
        image: redis:latest
        ports:
            - 6379:6379
    worker:
        build: .
        command: python manage.py rqworker
        volumes:
            - .:/code
        env_file:
            - .dockerenv
        depends_on:
            - db
            - redis
    ws:
        image: kjagiello/thunderpush
        env_file:
            - .dockerenv
        ports:
            - 8080:8080
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:80
        volumes:
            - .:/code
        ports:
            - 80:80
        env_file:
            - .dockerenv
        depends_on:
            - db
            - redis
        expose:
            - 80
