version: '2'

services:
    db:
        image: postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    redis:
        image: redis:latest
        ports:
            - 6379:6379
    worker:
        build: .
        command: /code/bin/worker
        volumes:
            - .:/code
        env_file:
            - .dockerenv
    web:
        build: .
        command: /code/bin/web
        volumes:
            - .:/code
        env_file:
            - .dockerenv
        expose:
            - 8000
        depends_on:
            - db
            - redis
    ws:
        image: kjagiello/thunderpush
        env_file:
            - .dockerenv
        ports:
            - 8080:8080
    nginx:
        image: nginx:latest
        volumes:
          - ./conf/nginx:/etc/nginx/conf.d
        ports:
          - 80:80
