# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 16:07
from __future__ import unicode_literals

from django.db import migrations, models
from uuid import uuid4


def forwards(apps, schema_editor):
    for episode in apps.get_model('hosting.Episode').objects.all():
        episode.guid = unicode(uuid4())
        episode.save(update_fields=('guid',))


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='guid',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.RunPython(
            forwards,
            backwards
        ),
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.CharField(max_length=36),
        )
    ]
