# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_url', models.URLField(max_length=512, verbose_name='app URL')),
                ('app_logo', models.URLField(blank=True, max_length=512, null=True)),
                ('source_token', models.CharField(max_length=255, unique=True)),
                ('secret_token', models.CharField(max_length=256, unique=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='hosting.Podcast')),
            ],
            options={
                'ordering': ('-last_fetched',),
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='app_logo',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='app_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='app URL'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='kind',
            field=models.CharField(choices=[(b'c', b'casual listener'), (b's', b'subscriber')], default='s', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio_filesize',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_filesize',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='public_token',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='secret_token',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='source_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set([('source_token', 'podcast')]),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('app_url', 'podcast')]),
        ),
    ]
