# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_episode_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='podcast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='hosting.Podcast'),
            preserve_default=False,
        ),
    ]
