# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_auto_20180212_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='kind',
            field=models.CharField(choices=[(b'trailer', b'trailer'), (b'episode', b'episode'), (b'bonus', b'bonus')], default='episode', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='number_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set([('number_bonus', 'number', 'kind', 'season')]),
        ),
    ]
